<template>
  <el-icon class="app-icon" aria-hidden="true"><component :is="resolvedIcon" /></el-icon>
</template>

<script setup lang="ts">
import {
  Aim,
  ArrowDown,
  ArrowUp,
  Bell,
  Box,
  Calendar,
  Camera,
  ChatDotRound,
  CircleCheck,
  CircleClose,
  CirclePlus,
  Coin,
  Collection,
  Compass,
  Connection,
  Cpu,
  CreditCard,
  DataAnalysis,
  Document,
  Edit,
  Folder,
  Goods,
  Grid,
  House,
  Key,
  Link,
  Lock,
  MagicStick,
  Menu,
  Monitor,
  Notification,
  Opportunity,
  Place,
  Pointer,
  Present,
  Promotion,
  QuestionFilled,
  Reading,
  Refresh,
  Right,
  School,
  Search,
  Sell,
  Service,
  Setting,
  Star,
  Suitcase,
  Ticket,
  Tools,
  TrendCharts,
  Trophy,
  UserFilled,
  Warning,
} from "@element-plus/icons-vue";
import { computed, type Component } from "vue";

const props = withDefaults(defineProps<{ name?: string; legacy?: string | null }>(), {
  name: "",
  legacy: "",
});

const icons: Record<string, Component> = {
  ai: MagicStick,
  "arrow-down": ArrowDown,
  "arrow-right": Right,
  "arrow-up": ArrowUp,
  announcement: Notification,
  announce: Notification,
  bell: Bell,
  board: Grid,
  bot: Cpu,
  box: Box,
  calendar: Calendar,
  camera: Camera,
  card: CreditCard,
  chart: DataAnalysis,
  check: CircleCheck,
  clock: Calendar,
  close: CircleClose,
  course: Reading,
  coursereview: Reading,
  database: Coin,
  desktop: Monitor,
  document: Document,
  edit: Edit,
  electric: Opportunity,
  folder: Folder,
  forum: ChatDotRound,
  gift: Present,
  hot: TrendCharts,
  key: Key,
  like: Pointer,
  link: Link,
  lock: Lock,
  market: Sell,
  menu: Menu,
  new: CirclePlus,
  pin: Place,
  price: Coin,
  promotion: Promotion,
  question: QuestionFilled,
  school: School,
  search: Search,
  service: Service,
  settings: Setting,
  condition: Goods,
  shield: Lock,
  star: Star,
  success: CircleCheck,
  sync: Refresh,
  target: Aim,
  ticket: Ticket,
  tools: Tools,
  trade: Connection,
  user: UserFilled,
  warning: Warning,
  work: Suitcase,
  "💬": ChatDotRound,
  "📢": Notification,
  "📣": Notification,
  "♻": Sell,
  "♻️": Sell,
  "🧭": Compass,
  "✨": MagicStick,
  "📊": DataAnalysis,
  "⭐": Star,
  "🔑": Key,
  "🎯": Aim,
  "💡": Opportunity,
  "🖥": Monitor,
  "🖥️": Monitor,
  "📚": Reading,
  "🔍": Search,
  "🔎": Search,
  "🏛": School,
  "🏛️": School,
  "🏫": School,
  "🎓": School,
  "📋": Document,
  "📝": Document,
  "📄": Document,
  "💼": Suitcase,
  "☰": Menu,
  "📅": Calendar,
  "🛠": Tools,
  "📸": Camera,
  "✅": CircleCheck,
  "❌": CircleClose,
  "👥": UserFilled,
  "🧩": Grid,
  "🛡": Lock,
  "🔄": Refresh,
  "🌐": Connection,
  "🎁": Present,
  "🎟": Ticket,
  "🎟️": Ticket,
  "🎫": Ticket,
  "💳": CreditCard,
  "💛": Star,
  "🤖": Cpu,
  "🚀": Promotion,
  "🗄": Coin,
  "🗂": Collection,
  "📦": Box,
  "📁": Folder,
  "⚙": Setting,
  "🔥": TrendCharts,
  "📌": Place,
  "📍": Place,
  "🆕": CirclePlus,
  "❓": QuestionFilled,
  "🌱": School,
  "🔒": Lock,
  "👍": Pointer,
  "💻": Monitor,
  "🛏": House,
  "🛏️": House,
  "👕": Goods,
  "🏸": Trophy,
  "🤝": Connection,
  "🕒": Calendar,
  "🚧": Warning,
};

const resolvedIcon = computed(() => icons[props.legacy || ""] || icons[props.name] || Grid);
</script>

<style scoped>
.app-icon { flex: 0 0 auto; vertical-align: -0.14em; }
</style>
