ALTER TABLE "User"
ALTER COLUMN "assistantPoints" TYPE DOUBLE PRECISION USING "assistantPoints"::DOUBLE PRECISION;

ALTER TABLE "CampusAssistantPointLedger"
ALTER COLUMN "delta" TYPE DOUBLE PRECISION USING "delta"::DOUBLE PRECISION,
ALTER COLUMN "balanceAfter" TYPE DOUBLE PRECISION USING "balanceAfter"::DOUBLE PRECISION;

ALTER TABLE "AiReviewLog"
ALTER COLUMN "pointCost" TYPE DOUBLE PRECISION USING "pointCost"::DOUBLE PRECISION;
