import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { createServer } from "node:http";
import test from "node:test";
import express from "express";

process.env.REDIS_ENABLED = "false";

test("shop access exposes only current active global-admin authority to the authenticated shop", async t => {
  const { prisma } = await import("../src/prisma");
  const { config } = await import("../src/config");
  const { shopIntegrationRouter } = await import("../src/routes/shopIntegration");
  const secret = "shop-access-test-secret-32-characters";
  const beforeSecret = config.shopIntegrationSecret;
  const beforeFind = prisma.user.findUnique;
  t.after(() => { config.shopIntegrationSecret = beforeSecret; prisma.user.findUnique = beforeFind; });
  config.shopIntegrationSecret = secret;
  let user: any = { role: "admin", status: "active" };
  let calls = 0;
  prisma.user.findUnique = (async ({ where, select }: any) => {
    calls++;
    assert.equal(where.id, 7);
    assert.deepEqual(select, { role: true, status: true });
    return user;
  }) as any;
  const app = express(); app.use(shopIntegrationRouter);
  app.use((err: any, _req: any, res: any, _next: any) => res.status(err.status || 400).json({ error: err.message }));
  const server = createServer(app);
  await new Promise<void>(resolve => server.listen(0, "127.0.0.1", resolve));
  t.after(() => new Promise<void>(resolve => server.close(() => resolve())));
  const endpoint = `http://127.0.0.1:${(server.address() as any).port}/dayi-shop/users/7/access`;
  const get = (key = secret) => fetch(endpoint, { headers: { "x-shop-integration-secret": key } });
  assert.equal((await get("wrong")).status, 401);
  assert.equal(calls, 0);
  assert.equal((await fetch(endpoint.replace('/7/', '/0/'), { headers: { "x-shop-integration-secret": secret } })).status, 400);
  const response = await get();
  assert.equal(response.headers.get("cache-control"), "no-store");
  assert.deepEqual((await response.json()).data, { userId: 7, globalAdmin: true });
  for (const role of ["user", "mod", "bot"]) {
    user = { role, status: "active", voiceHubRole: "super_admin" };
    assert.equal((await (await get()).json()).data.globalAdmin, false);
  }
  for (const status of ["banned", "deleting", "deleted"]) {
    user = { role: "admin", status };
    assert.equal((await (await get()).json()).data.globalAdmin, false);
  }
  user = null;
  assert.equal((await (await get()).json()).data.globalAdmin, false);
});

test("shop events are authenticated, private, idempotent and ignore unavailable accounts", async t => {
  const { prisma } = await import("../src/prisma");
  const { config } = await import("../src/config");
  const { shopIntegrationRouter } = await import("../src/routes/shopIntegration");
  const replace = (target: any, key: string, value: any) => { const before = target[key]; target[key] = value; t.after(() => { target[key] = before; }); };
  const secret = "shop-integration-test-secret-32-bytes";
  replace(config, "shopIntegrationSecret", secret);
  const messages: any[] = [];
  replace(prisma.user, "findUnique", async ({ where }: any) => where.id === 7 ? { status: "active" } : null);
  let queue = Promise.resolve();
  replace(prisma, "$transaction", (fn: any) => { const work = queue.then(() => fn(prisma)); queue = work.catch(() => undefined); return work; });
  replace(prisma, "$executeRaw", async () => 1);
  replace(prisma.notification, "findFirst", async ({ where }: any) => messages.find(m => m.userId === where.userId && m.payload.includes(where.payload.contains)) || null);
  replace(prisma.notification, "create", async ({ data }: any) => { messages.push(data); return data; });
  const app = express(); app.use(express.json(), shopIntegrationRouter);
  app.use((err: any, _req: any, res: any, _next: any) => res.status(err.status || 400).json({ error: err.message }));
  const server = createServer(app);
  await new Promise<void>(resolve => server.listen(0, "127.0.0.1", resolve));
  t.after(() => new Promise<void>(resolve => server.close(() => resolve())));
  const endpoint = `http://127.0.0.1:${(server.address() as any).port}/dayi-shop/notifications`;
  const event = { userId: 7, orderId: 123, orderNo: "DJ123", status: "paid" };
  const send = (notifications: any[], key = secret) => fetch(endpoint, { method: "POST", headers: { "content-type": "application/json", "x-shop-integration-secret": key }, body: JSON.stringify({ notifications }) });
  assert.equal((await send([event], "wrong")).status, 401);
  for (const data of [{ ...event, userId: 0 }, { ...event, link: "https://evil.test" }, { ...event, orderNo: "../../evil" }]) assert.equal((await send([data])).status, 400);
  const retried = await Promise.all([send([event]), send([event])]);
  assert.ok(retried.every(r => r.status === 200));
  assert.equal(messages.length, 1);
  assert.equal(messages[0].userId, 7);
  assert.equal(messages[0].category, "service-tool");
  assert.equal(messages[0].link, "https://shop.cputime.cn/orders/DJ123");
  assert.equal(messages[0].source, "大义软商");
  assert.equal((await (await send([{ ...event, userId: 8 }])).json()).data.skipped, 1);
  for (const refundRecordId of [41, 42]) assert.equal((await send([{ ...event, status: "partially_refunded", refundRecordId }])).status, 200);
  assert.equal(messages.length, 3);
});

test("shop OAuth enforces callback, client secret, PKCE, single-use codes and profile-only access", async t => {
  const { config } = await import("../src/config");
  const { prisma } = await import("../src/prisma");
  const { oauthRouter } = await import("../src/routes/oauth");
  const { oauthClientIsValid, oauthScopesAllowed } = await import("../src/services/oauthClients");
  const replace = (target: any, key: string, value: any) => { const before = target[key]; target[key] = value; t.after(() => { target[key] = before; }); };
  const secret = "shop-oauth-test-secret-32-characters";
  replace(config, "shopIntegrationSecret", secret);
  const callback = "https://shop.cputime.cn/api/v1/auth/cputime/callback";
  assert.equal(oauthClientIsValid("dayi-shop", callback), true);
  for (const uri of ["https://shop.cputime.cn/other", callback + "?x=1", "https://evil.test/callback", callback + "#x", "http://shop.cputime.cn/api/v1/auth/cputime/callback"]) assert.equal(oauthClientIsValid("dayi-shop", uri), false);
  assert.equal(oauthScopesAllowed("dayi-shop", ["openid", "profile"]), true);
  assert.equal(oauthScopesAllowed("dayi-shop", ["ai"]), false);
  const originalOrigin = config.shopOrigin;
  const originalMode = config.nodeEnv;
  config.shopOrigin = "http://127.0.0.1:18089";
  config.nodeEnv = "production";
  assert.equal(oauthClientIsValid("dayi-shop", config.shopOrigin + "/api/v1/auth/cputime/callback"), false);
  config.nodeEnv = "test";
  assert.equal(oauthClientIsValid("dayi-shop", config.shopOrigin + "/api/v1/auth/cputime/callback"), true);
  config.shopOrigin = originalOrigin;
  config.nodeEnv = originalMode;
  const verifier = "a".repeat(43);
  const record: any = { id: 1, userId: 7, clientId: "dayi-shop", redirectUri: callback, scope: "openid profile", codeChallenge: createHash("sha256").update(verifier).digest("base64url"), expiresAt: new Date(Date.now() + 60000), usedAt: null };
  let status = "active";
  replace(prisma.user, "findUnique", async () => ({ status }));
  replace(prisma.oAuthAuthorizationCode, "findUnique", async () => record);
  replace(prisma.oAuthAuthorizationCode, "updateMany", async () => { if (record.usedAt) return { count: 0 }; record.usedAt = new Date(); return { count: 1 }; });
  replace(prisma.oAuthAccessToken, "create", async ({ data }: any) => data);
  replace(prisma.oAuthAccessToken, "findUnique", async () => ({ userId: 7, clientId: "dayi-shop", scope: "openid profile", expiresAt: new Date(Date.now() + 10000), user: { id: 7, nickname: "Test buyer", avatar: null, status } }));
  replace(prisma.oAuthAccessToken, "update", async () => ({}));
  const app = express(); app.use(express.json(), oauthRouter);
  app.use((err: any, _req: any, res: any, _next: any) => res.status(err.status || 400).json({ error: err.message }));
  const server = createServer(app);
  await new Promise<void>(resolve => server.listen(0, "127.0.0.1", resolve));
  t.after(() => new Promise<void>(resolve => server.close(() => resolve())));
  const origin = `http://127.0.0.1:${(server.address() as any).port}`;
  const body = { grant_type: "authorization_code", code: "b".repeat(64), client_id: "dayi-shop", redirect_uri: callback, code_verifier: verifier, client_secret: secret };
  const exchange = (overrides = {}) => fetch(origin + "/token", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...body, ...overrides }) });
  assert.equal((await exchange({ client_secret: "wrong" })).status, 401);
  assert.equal((await exchange({ code_verifier: "c".repeat(43) })).status, 400);
  status = "deleted";
  assert.equal((await exchange()).status, 403);
  assert.equal(record.usedAt, null);
  status = "active";
  assert.equal((await exchange()).status, 200);
  assert.equal((await exchange()).status, 400);
  const profile = await fetch(origin + "/userinfo", { headers: { Authorization: "Bearer test" } });
  assert.equal(profile.status, 200);
  assert.deepEqual((await profile.json()).data, { sub: "7", user: { id: 7, nickname: "Test buyer", avatar: null } });
  for (status of ["banned", "deleting", "deleted"]) assert.equal((await fetch(origin + "/userinfo", { headers: { Authorization: "Bearer test" } })).status, 403);
});
